version: '3.8'

services:
  web:
    build:
      context:  ./  # Specify the path to your project root
      dockerfile: ./Dockerfile  # Specify the path to your Dockerfile relative to the context
    command: >
            sh -c "python task_management/manage.py migrate &&
                python task_management/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env  # Specify the path to your .env file relative to the project root
    depends_on:
      - db

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: mydbuser
      POSTGRES_PASSWORD: mydbpassword
      POSTGRES_DB: mydbname
    volumes:
      - postgres_data:/var/lib/postgresql13/data

volumes:
  postgres_data:
